##############################################################################
# Genome and project-specific files that will change from project-to-project
##############################################################################

### Point gtf and indices to either human or mouse.

# GTF file for the genome build you would like to use
gtf_file:
  /home/groups/MaxsonLab/indices/GRch38/STAR_index/Homo_sapiens.GRCh38.104.gtf
# Bed file for rseqc function read_distribution
bed_file:
  /home/groups/MaxsonLab/indices/GRch38/STAR_index/Homo_sapiens.GRCh38.104.bed
# Pre-built STAR index
star_index:
  /home/groups/MaxsonLab/indices/GRch38/STAR_index
filter_anno:
  anno/biomaRt/hg38.Ens_90.biomaRt.geneAnno.Rdata
gene_names:
  data/hg38_Ens102_genes.txt

####################################################################
# Tool-specific files that will not change from project-to-project
####################################################################

# Fasta file including Illumina adapters to be trimmed out via bbduk
bb_adapter:
  data/adapters.fa
# Pre-built genome indexes for various organisms which we will screen against to look for contamination
conf:
  data/fastq_screen.conf

##########################################
# Important project-specific paths/files
##########################################

# Metadata needed for differential expression analysis
omic_meta_data:
# tab delimited file
  data/metadata.txt

##############################################################################################
# Project-specific specifications you will need to make prior to submission of the pipeline
##############################################################################################

# Biotypes you would like to include in your gene counts table
# Example: protein_coding,lincRNA,sRNA,rRNA,snRNA,snoRNA
biotypes:
  "protein_coding" ### if you want to keep all biotypes, use ""

# Unique project identifier which will be concatenated onto your counts table file name.
project_id:
  "Patient24"
# Genome assembly used for GO analysis, format must be as below, with the genome assembly first, and the version of ensembl second, separated by a period (Unless there is only one ensembl version, then just write assembly).
# Currently allowed assembly options (as of 4/25/22): mm10, hg19, hg38.89, or hg38.90
assembly:
  hg38.90
# remove mito genes (1/0)
mito:
  1
# option to print GO term tree (0/1)
printTree:
  1
# fold change cutoff (not log2 transformed) for GO analysis and volcano pot
FC:
  2
# FDR adjusted p-value cutoff for GO analysis and volcano plot
adjp:
  0.01
seq_layout:
  PE
# The column name of the characteristic you would like to do DE on. Example: Diagnosis, genotype, etc. This must be a column in your omic_meta_data.
linear_model:
  #Column name in meta data file to generate contrasts by
  Condition
# The column name in which your sampleIDs are defined in omic_meta_data. These should match the sampleIDs in your fastq files.
sample_id:
  #Column name listing unique sample ids to be used. This needs to be the first column in the meta data file
  SampleID
# The column names in your omic_meta_data file which you would like to annotate your heatmaps by. This is used as a QC to look for batch effects. Enter columns which could potentially introduce a batch effect in your data.
meta_columns_to_plot:
  Condition: Condition
pca:
  labels:
    #Column name in meta data file to generate group files and comparisons
    - Condition
# Contrasts which you would like to run differential expression on.
# For example if you want to look at wild type (wt) vs. mutant (mut), you would specify mut-vs-wt
# It is important that when listing your types here, you write your baseline SECOND
diffexp:
  # contrasts to generate group files and perform comparisons
  contrasts:
    - GSK-vs-DMSO
    - QUIZ-vs-DMSO
    - COMBO-vs-DMSO
      
  # This option is specified if you would like to run DESeq2 on a subset of your samples (> pairwise comparison)
  LRT:
    - GSK
    - COMBO
    - QUIZ
    - DMSO

# If you would like to colour your QC plots by an RColorBrewer palette, list that palette under the rcolorbrewer parameter, otherwise, write "NA"
# If you would like to colour your QC plots by specific colours, please list them under the discrete category, with one colour for each bullet point
## The discrete colours will be assigned to your Conditions (ie. linear_model) in the order that they show up in your metadata table, when it is ordered alphabetically by sample ID
## There must be the same number of colours listed as there are Conditions
# If no options are specified, the default ggplot2 colours are used
colors:
  rcolorbrewer:
    - NA
  discrete:
    - NA
